views:
  - !include lovelace/00_secure.yaml
  - !include lovelace/01_main.yaml
  - !include lovelace/02_weather.yaml
  - !include lovelace/03_kitchen_living_room.yaml
  - !include lovelace/04_1st_floor_bedroom.yaml
  - !include lovelace/05_2nd_floor_bedroom.yaml
  - !include lovelace/06_toilet.yaml
  - !include lovelace/07_porch.yaml
  - !include lovelace/07_telegramm.yaml
  - !include lovelace/08_cameras.yaml